server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

compactor:
  compaction:
    compacted_block_retention: 48h

ingester:
  max_block_bytes: 104857600
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /var/tempo
    wal:
      path: /var/tempo/wal

